### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/zenodo#7]
Asking because of its resource at Transifex.

Please provide feedback.

**Comment by rakekniven** [comment]
@daita Can you answer my question?

**Comment by e-alfred** [comment]
Losing this app is surely not good regarding the acceptance of Nextcloud in the scientific community.

**Comment by rakekniven** [comment]
Ping

**Comment by daita** [comment]
A new version have been published: https://apps.nextcloud.com/apps/zenodo

**Comment by rakekniven** [comment]
@daita  Just seen you made release v1.1.1 and closed the issue.
Would be nice to hear some words from you regarding the activity.

Was it just a maintain release for new NC versions?
Couldn't find any release notes ...

**Comment by daita** [comment]
yes, it is a new release for compat with newer version of NC. I have tested and it is working. No changes have been made on the app itself.

**Comment by rakekniven** [comment]
Adapted https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312
